backend/race/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('get-races-for-event/<int:event_id>/', views.get_races_for_event, name='get-races-for-event'),
    path('', views.MainPageView.as_view(), name='main_page'),
    path('events/', views.EventsView.as_view(), name='events'),
    path('pricing/', views.PricingView.as_view(), name='pricing'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('event-detail/<slug:event_slug>/',
         views.EventDetailView.as_view(), name='event_detail'),
    path('event-detail/<slug:event_slug>/registrations/',
         views.EventRegistrationsView.as_view(), name='event_registrations'),

    path('events/<int:pk>/add_review/', views.add_review, name='add_review'),

    path('register-for-event/', views.EventRegistrationCreateView.as_view(), name='register_for_event'),
    path('race-registration-success/', views.RaceRegistrationSuccessView.as_view(), name='race_registration_success'),


    # path('register-for-event/', views.register_for_event, name='register_for_event'),

]

backend/race_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_email_verification import urls as email_urls


from django.conf import settings
from race.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('email/', include(email_urls), name='email_verification'),
    path('', include('race.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

# handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Организация любительских забегов"

backend/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.shortcuts import render
from django.urls import path, reverse_lazy
from . import views


app_name = "users"

urlpatterns = [
    path('register/', views.RegisterUser.as_view(),
         name='register'),

    path('email-verification-sent/',
         lambda request: render(request, 'users/email/email_verification_sent.html'),
         name='email_verification_sent'),

    path('login/', views.LoginUser.as_view(),
         name='login'),

    path('logout/', LogoutView.as_view(),
         name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(),
         name="password_change"),

    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name="users/password_change_done.html"),
        name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(
        template_name="users/password_reset_form.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done")),
        name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html"),
        name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        success_url=reverse_lazy("users:password_reset_complete")),
        name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"),
        name='password_reset_complete'),

    path('profile/', views.ProfileUser.as_view(),
         name='profile'),

    path('registrations-list/', views.RegistrationsListView.as_view(),
         name='registrations_list'),

    path('registration-detail/<int:pk>/', views.RegistrationDetailView.as_view(),
         name='registration_detail'),

    path('registration/toggle-status/<int:pk>/', views.ToggleRegistrationStatusView.as_view(),
         name='registration_toggle_status'),

    path('delete-profile/', views.DeleteProfileView.as_view(),
         name='delete_profile'),
]

backend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name="Фотография")
    date_birth = models.DateField(blank=True, null=True, verbose_name="Дата рождения")
    email = models.EmailField(unique=True, blank=False)

backend/users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    """Form class used for user login"""
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    """
    Form class used for user registration.
    """
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    date_birth = forms.DateField(
        widget=forms.widgets.DateInput(attrs={'placeholder': '20.01.1979'}),
        label='Дата рождения'
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'date_birth', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин')
    email = forms.CharField(disabled=True, label='E-mail')
    date_birth = forms.DateField(
        widget=forms.widgets.DateInput(attrs={'placeholder': '20.01.1979'}),
        label='Дата рождения'
    )

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

backend/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from race_project import settings
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm
from race.models import EventRegistration

from django_email_verification import send_email


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


# class RegisterUser(CreateView):
#     form_class = RegisterUserForm
#     template_name = 'users/register.html'
#     extra_context = {'title': "Регистрация"}
#     success_url = reverse_lazy('users:login')

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:email_verification_sent')  # URL-адрес для перенаправления после регистрации

    def form_valid(self, form):
        # Создаем пользователя, но пока не сохраняем в базу данных
        user = form.save(commit=False)
        # Устанавливаем пользователя как неактивного
        user.is_active = False
        # Сохраняем пользователя
        user.save()
        # Отправляем email для верификации
        send_email(user)
        # Вызываем родительский метод form_valid
        return super().form_valid(form)


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {
        'title': "Профиль пользователя",
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        # Возвращаем текущего пользователя для обновления
        return self.request.user


class UserPasswordChange(LoginRequiredMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"


class RegistrationsListView(LoginRequiredMixin, ListView):
    """A view for listing a user's event registrations."""
    model = EventRegistration
    template_name = 'users/registrations_list.html'
    context_object_name = 'registrations'
    paginate_by = 5

    def get_queryset(self):
        # Получение регистраций
        return self.request.user.registrations.order_by('-registered_at')


class RegistrationDetailView(LoginRequiredMixin, DetailView):
    """A view for displaying the details of an individual event registration."""
    model = EventRegistration
    template_name = 'users/registration_detail.html'
    context_object_name = 'registration'

    def get_queryset(self):
        # Убедитесь, что пользователи могут видеть только свои регистрации
        return EventRegistration.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()  # Добавление текущего времени в контекст
        return context


class ToggleRegistrationStatusView(LoginRequiredMixin, View):
    def post(self, request, pk):
        registration = get_object_or_404(EventRegistration, pk=pk, user=request.user, event__start_datetime__gte=timezone.now())

        if registration:
            registration.is_active = not registration.is_active
            registration.save()
            message = "Регистрация успешно отменена." if not registration.is_active else "Регистрация восстановлена."
            messages.success(request, message)
        else:
            messages.error(request, "Не удалось изменить статус регистрации.")

        return HttpResponseRedirect(reverse_lazy('users:registration_detail', kwargs={'pk': pk}))


class DeleteProfileView(LoginRequiredMixin, View):
    template_name = 'users/delete_profile.html'
    success_url = reverse_lazy('main_page')  # URL для перенаправления после удаления

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        user = request.user
        user.delete()
        messages.success(request, 'Ваш аккаунт успешно удален.')
        return redirect(self.success_url)

backend/users/templates/users/delete_profile.html
{% extends 'users/user_menu.html' %}

{% block user_content %}
<div class="container bg-white shadow  p-5">
    <h5>Вы уверены, что хотите удалить свой аккаунт?</h5>
    <br>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-block p-2">Удалить аккаунт</button>
    </form>
</div>
{% endblock user_content %}

backend/users/templates/users/login.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="mb-4 text-center">Авторизация</h2>
            <form method="post" class="card p-4">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />

                {% if form.non_field_errors %}
                    <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                {% endif %}

                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% if field.errors %}
                            <div class="invalid-feedback d-block">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endfor %}

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Войти</button>
                </div>

                <div class="mt-3 text-center">
                    Еще нет аккаунта? <a href="{% url 'users:register' %}">Регистрация</a>
                </div>

                <div class="mt-3 text-center">
                    <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_change_form.html
{% extends 'users/user_menu.html' %}
{% load widget_tweaks %}

{% block user_content %}
<div class="container mt-4">
    <h5>Изменить пароль</h5>
    <form method="post" class="mt-3">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
        {% endif %}

        {% for f in form %}
            <div class="mb-3">
                <label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>
                {{ f|add_class:"form-control" }}
                {% if f.errors %}
                    <div class="invalid-feedback d-block">{{ f.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Изменить пароль</button>
    </form>
</div>
{% endblock user_content %}

backend/users/templates/users/password_reset_complete.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h2 class="display-4">Пароль изменен</h2>
            <p class="lead">
                Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для <a href="{% url 'users:login' %}">входа в систему</a>.
            </p>
        </div>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_reset_confirm.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="mb-4 text-center">Новый пароль</h2>
            <form method="post" class="card p-4">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                {% endif %}

                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% if field.errors %}
                            <div class="invalid-feedback d-block">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endfor %}

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_reset_done.html
{% extends 'layouts/base.html' %}
{% load i18n %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h2 class="display-4">Сброс пароля</h2>
            <p class="lead">
                {% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}
            </p>
            <p class="lead">
                {% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}
            </p>
        </div>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

backend/users/templates/users/password_reset_form.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="mb-4 text-center">Восстановление пароля</h2>
            <form method="post" class="card p-4">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                {% endif %}

                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% if field.errors %}
                            <div class="invalid-feedback d-block">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endfor %}

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Сбросить по E-mail</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/users/templates/users/profile.html
{% extends 'users/user_menu.html' %}
{% load widget_tweaks %}

{% block user_content %}
<div class="container mt-4 mb-5">
    <h5>Редактировать профиль</h5>
    <form method="post" enctype="multipart/form-data" class="mt-3">
        {% csrf_token %}
        <div class="row mb-3">
            <div class="col-md-12">
                {% if user.photo %}
                    <img src="{{ user.photo.url }}" class="img-thumbnail mb-3" style="max-width: 150px; max-height: 150px;">
                {% else %}
                    <img src="{{ default_image }}" class="img-thumbnail mb-3" style="max-width: 150px; max-height: 150px;">
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {% if form.non_field_errors %}
                    <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                {% endif %}

                {% for f in form %}
                    <div class="mb-3">
                        <label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>
                        {{ f|add_class:"form-control" }}
                        {% if f.errors %}
                            <div class="invalid-feedback d-block">{{ f.errors }}</div>
                        {% endif %}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>
    </form>
</div>
{% endblock user_content %}

backend/users/templates/users/register.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-4 mb-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="mb-4 text-center">Регистрация</h2>
            <form method="post" class="card p-4">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />

                {% if form.non_field_errors %}
                    <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                {% endif %}

                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% if field.errors %}
                            <div class="invalid-feedback d-block">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endfor %}

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </div>

                <div class="mt-3 text-center">
                    Уже есть аккаунт? <a href="{% url 'users:login' %}">Войти</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/users/templates/users/register_done.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4 text-center">Добро пожаловать!</h1>
            <p class="lead text-center">
                Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по
                <a href="{% url 'users:login' %}">этой ссылке</a>.
            </p>
        </div>
    </div>
</div>
{% endblock %}

backend/users/templates/users/registration_detail.html
{% extends 'users/user_menu.html' %}
{% load widget_tweaks %}

{% block user_content %}
<div class="container mt-4">
    <h5>Детали регистрации</h5>
    <div class="card mb-3">
        <div class="card-body">
            <p class="card-text"><strong>Статус регистрации:</strong> {{ registration.is_active|yesno:"Активна,Отменена" }}</p>
            <h3 class="card-title">{{ registration.event.title }}</h3>
            <p class="card-text"><strong>Дата забега:</strong> {{ registration.event.start_datetime|date:"d F Y г. (D)" }}</p>
            <p class="card-text"><strong>Время начала:</strong> {{ registration.event.start_datetime|time }}</p>
            <p class="card-text"><strong>Место проведения:</strong> {{ registration.event.location }}</p>
            <p class="card-text"><strong>Категория:</strong> {{ registration.race }}</p>
            <p class="card-text"><strong>Статус оплаты:</strong> {{ registration.payment_confirmation|yesno:"Подтверждена,Не подтверждена" }}</p>
            <p class="card-text"><strong>Размер футболки:</strong> {{ registration.tshirt_size }}</p>
            <p class="card-text"><strong>Зарегистрировано:</strong> {{ registration.registered_at|date:"d.m.Y H:i" }}</p>
            <a href="{{ registration.payment_document.url }}" download>Скачать документ об оплате</a>

            <!-- Позиционирование кнопки в правом нижнем углу карточки -->
            <div class="d-flex mt-4">
                {% if registration.event.start_datetime >= now %}
                    <form action="{% url 'users:registration_toggle_status' registration.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-warning btn-sm">
                            {% if registration.is_active %}
                                Отменить регистрацию
                            {% else %}
                                Восстановить регистрацию
                            {% endif %}
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
    <a href="{% url 'users:registrations_list' %}" class="btn btn-secondary">Вернуться к регистрациям</a>
</div>
{% endblock user_content %}

backend/users/templates/users/registrations_list.html
{% extends 'users/user_menu.html' %}
{% load widget_tweaks %}

{% block user_content %}
<div class="container mt-4">
    <h5 class="mb-4">Личные регистрации</h5>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Мероприятие</th>
                <th scope="col">Дата</th>
                <th scope="col">Статус регистрации</th>
                <th scope="col">Статус оплаты</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <!-- Предположим, что 'registrations' - это список регистраций пользователя -->
            {% for registration in registrations %}
            <tr>
                <td>{{ registration.event.title }}</td>
                <td>{{ registration.event.date|date:"d.m.Y" }}</td>
                <td>{{ registration.is_active|yesno:"Активна,Отменена" }}</td>
                <td>{{ registration.payment_confirmation|yesno:"Подтверждена,Не подтверждена" }}</td>
                <td>
                    <a href="{% url 'users:registration_detail' registration.id %}" class="btn btn-primary btn-sm">Подробнее</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">У вас пока нет регистраций на забеги.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Пагинация -->
    <div class="row">
        <div class="col d-flex justify-content-center mt-4">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% for page_num in paginator.page_range %}
                        <li class="page-item {% if page == page_num %}active{% endif %}">
                            <a class="page-link" href="?page={{ page_num }}{% if filter %}&filter={{ filter }}{% endif %}">{{ page_num }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock user_content %}

backend/users/templates/users/user_menu.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <!-- Панель навигации пользователя -->
        <div class="col-md-4">
            <!-- Ссылки меню -->
            <div class="list-group">
                <a href="{% url 'users:registrations_list' %}" class="list-group-item list-group-item-action">Личные регистрации</a>
                <a href="{% url 'users:profile' %}" class="list-group-item list-group-item-action">Редактировать профиль</a>
                <a href="{% url 'users:password_change' %}" class="list-group-item list-group-item-action">Изменить пароль</a>
                <a href="{% url 'users:delete_profile' %}" class="list-group-item list-group-item-action">Удалить аккаунт</a>
                <a href="{% url 'users:logout' %}" class="list-group-item list-group-item-action text-danger">Выход</a>
            </div>
        </div>
        <!-- Контентная область -->
        <div class="col-md-8">
            <h3>Добро пожаловать, {{ request.user.get_full_name|default:request.user.username }} !</h3>
            {% block user_content %}
            <!-- Сюда будет вставляться динамический контент -->
            {% endblock user_content %}
        </div>
    </div>
</div>
{% endblock content %}