backend/race/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('get-races-for-event/<int:event_id>/', views.get_races_for_event, name='get-races-for-event'),
    path('', views.MainPageView.as_view(), name='main_page'),
    path('events/', views.EventsView.as_view(), name='events'),
    path('pricing/', views.PricingView.as_view(), name='pricing'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('event-detail/<slug:event_slug>/',
         views.EventDetailView.as_view(), name='event_detail'),
    path('event-detail/<slug:event_slug>/registrations/',
         views.EventRegistrationsView.as_view(), name='event_registrations'),

    path('events/<int:pk>/add_review/', views.add_review, name='add_review'),

    path('register-for-event/', views.EventRegistrationCreateView.as_view(), name='register_for_event'),
    path('race-registration-success/', views.RaceRegistrationSuccessView.as_view(), name='race_registration_success'),


    # path('register-for-event/', views.register_for_event, name='register_for_event'),

]

backend/race_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_email_verification import urls as email_urls


from django.conf import settings
from race.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('email/', include(email_urls), name='email_verification'),
    path('', include('race.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

# handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Организация любительских забегов"

backend/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.shortcuts import render
from django.urls import path, reverse_lazy
from . import views


app_name = "users"

urlpatterns = [
    path('register/', views.RegisterUser.as_view(),
         name='register'),

    path('email-verification-sent/',
         lambda request: render(request, 'users/email/email_verification_sent.html'),
         name='email_verification_sent'),

    path('login/', views.LoginUser.as_view(),
         name='login'),

    path('logout/', LogoutView.as_view(),
         name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(),
         name="password_change"),

    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name="users/password_change_done.html"),
        name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(
        template_name="users/password_reset_form.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done")),
        name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html"),
        name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        success_url=reverse_lazy("users:password_reset_complete")),
        name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"),
        name='password_reset_complete'),

    path('profile/', views.ProfileUser.as_view(),
         name='profile'),

    path('registrations-list/', views.RegistrationsListView.as_view(),
         name='registrations_list'),

    path('registration-detail/<int:pk>/', views.RegistrationDetailView.as_view(),
         name='registration_detail'),

    path('registration/toggle-status/<int:pk>/', views.ToggleRegistrationStatusView.as_view(),
         name='registration_toggle_status'),

    path('delete-profile/', views.DeleteProfileView.as_view(),
         name='delete_profile'),
]

backend/race/models.py
"""
Database models.
"""
from django.urls import reverse
from django.utils import timezone
from django.db import models
import uuid
import os

import requests
from urllib.parse import urlencode


import logging

from django.utils.text import slugify

from race_project import settings
from phonenumber_field.modelfields import PhoneNumberField

logger = logging.getLogger(__name__)


def payment_docs_file_path(instance, filename):
    """Generate file path for new payment document."""
    event_slug = str(instance.event.slug).replace('-', '_')
    ext = os.path.splitext(filename)[1]
    filename = f'{uuid.uuid4()}{ext}'

    return os.path.join('uploads', 'payment_docs', event_slug, filename)


def event_image_file_path(instance, filename):
    """Generate file path for event image using the event slug and original filename."""
    event_slug = str(instance.slug).replace('-', '_')
    return os.path.join('events', 'image', event_slug, filename)


def event_protocol_file_path(instance, filename):
    """Generate file path for event protocol using the event slug and original filename."""
    event_slug = str(instance.event.slug).replace('-', '_')
    return os.path.join('events', 'protocol', event_slug, filename)


def event_photos_file_path(instance, filename):
    """Generate file path for event photos using the event slug and original filename."""
    event_slug = str(instance.event.slug).replace('-', '_')
    return os.path.join('events', 'photos', event_slug, filename)


class RaceType(models.Model):
    """Model representing a race type or category."""
    DISTANCE_CHOICES = [
        (5, '5 км'),
        (10, '10 км'),
        (15, '15 км'),
        (20, '20 км'),
    ]
    GENDER_CHOICES = [
        ('M', 'Муж.'),
        ('F', 'Жен.'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Пол")
    min_age = models.PositiveSmallIntegerField(verbose_name="Минимальный возраст")
    distance = models.PositiveSmallIntegerField(choices=DISTANCE_CHOICES, verbose_name="Дистанция")
    registration_fee = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Стоимость регистрации")

    def __str__(self):
        return f"{self.distance} км {self.get_gender_display()} {self.min_age} лет и старше (взнос {self.registration_fee} руб.)"

    class Meta:
        verbose_name = "Тип забега"
        verbose_name_plural = "Типы забегов"


class Location(models.Model):
    """Model representing a location address of sports event."""
    street = models.CharField(max_length=256, verbose_name="Улица")
    house_number = models.CharField(max_length=20, blank=True, null=True, verbose_name="Номер дома")
    city = models.CharField(max_length=256, verbose_name="Город")
    postal_code = models.CharField(max_length=6, verbose_name="Почтовый индекс")
    country = models.CharField(max_length=100, verbose_name="Страна")
    latitude = models.FloatField(blank=True, null=True, verbose_name="Широта")
    longitude = models.FloatField(blank=True, null=True, verbose_name="Долгота")

    def __str__(self):
        return f"{self.street}, {self.house_number}, {self.city}, {self.postal_code}, {self.country}"

    def save(self, *args, **kwargs):
        """Save method for getting the coordinates if they are not already set."""
        if not (self.latitude and self.longitude):
            self.latitude, self.longitude = self.geocode_address()
        super().save(*args, **kwargs)

    def geocode_address(self):
        """Method for geocoding the location address using Nominatim from OpenStreetMap."""
        params = {
            'format': 'json',
            'street': f"{self.street} {self.house_number}",
            'city': self.city,
            'postalcode': self.postal_code,
            'country': self.country,
        }
        url = f"https://nominatim.openstreetmap.org/search?{urlencode(params)}"
        response = requests.get(url)
        if response.status_code == 200:
            results = response.json()
            if results:
                return float(results[0]['lat']), float(results[0]['lon'])
        return None, None

    class Meta:
        verbose_name = "Место проведения"
        verbose_name_plural = "Места проведения"


class Event(models.Model):
    """Model representing a sports event."""
    EVENT_TYPES = [
        ("trail", "Трейл"),
        ("cross", "Кросс"),
        ("mountain", "Горный"),
        ("road", "Дорожный"),
        # Добавьте другие типы событий при необходимости
    ]
    title = models.CharField(max_length=255, verbose_name="Название мероприятия")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL-имя для мероприятия")
    description = models.TextField(verbose_name="Описание мероприятия")
    event_rules = models.TextField(verbose_name="Условия участия")
    event_type = models.CharField(max_length=50, choices=EVENT_TYPES, verbose_name="Тип мероприятия")
    start_datetime = models.DateTimeField(verbose_name="Начало мероприятия", db_index=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, verbose_name="Место проведения мероприятия")
    total_slots = models.PositiveIntegerField(verbose_name="Всего мест")
    is_upcoming = models.BooleanField(default=True, verbose_name="Предстоящее мероприятие")
    image = models.ImageField(upload_to=event_image_file_path, verbose_name="Изображение для мероприятия")
    race_types = models.ManyToManyField(RaceType, verbose_name="Участвующие группы")

    def get_absolute_url(self):
        """Getting the absolute event URL."""
        return reverse('event_detail', kwargs={'event_slug': self.slug})

    def get_registrations_url(self):
        """Получение абсолютного URL для страницы регистраций мероприятия."""
        return reverse('event_registrations', kwargs={'event_slug': self.slug})

    def days_left(self):
        """Return days left for the event."""
        delta = self.start_datetime.date() - timezone.now().date()
        return delta.days

    def get_free_slots(self):
        """Returns quantity of free slots or the event."""
        registrations_count = EventRegistration.objects.filter(event=self, is_active=True).count()
        return self.total_slots - registrations_count

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Мероприятие"
        verbose_name_plural = "Мероприятия"


# class EventRegistration(models.Model):
#     """Model representing a user's registration for a race."""
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
#                              verbose_name="Пользователь", related_name="registrations")
#     event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name="Мероприятие")
#     race = models.ForeignKey(RaceType, on_delete=models.CASCADE, verbose_name="Участвующие группы")
#     payment_document = models.FileField(upload_to=payment_docs_file_path, verbose_name="Документ об оплате")
#     date_of_birth = models.DateField(verbose_name="Дата рождения")
#     city = models.CharField(max_length=255, verbose_name="Город")
#     club = models.CharField(max_length=255, blank=True, null=True, verbose_name="Клуб")
#     tshirt_size = models.CharField(max_length=3, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], verbose_name="Размер футболки")
#     payment_confirmation = models.BooleanField(default=False, verbose_name="Подтверждение оплаты")
#     registered_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")
#     is_active = models.BooleanField(default=True, verbose_name="Активная регистрация")
#
#     def __str__(self):
#         return f"Регистрация {self.user} на {self.race} в мероприятии {self.event}"
#
#     class Meta:
#         verbose_name = "Регистрация на забег"
#         verbose_name_plural = "Регистрации на забеги"


class EventRegistration(models.Model):
    """Model representing a user's registration for a race."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             verbose_name="Пользователь", related_name="registrations")
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name="Мероприятие")
    race = models.ForeignKey(RaceType, on_delete=models.CASCADE, verbose_name="Участвующие группы")
    payment_document = models.FileField(upload_to=payment_docs_file_path, verbose_name="Документ об оплате")
    phone_number = PhoneNumberField(blank=True, null=True, verbose_name="Номер телефона")
    city = models.CharField(max_length=255, verbose_name="Город")
    club = models.CharField(max_length=255, blank=True, null=True, verbose_name="Клуб")
    tshirt_size = models.CharField(max_length=3, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], verbose_name="Размер футболки")
    payment_confirmation = models.BooleanField(default=False, verbose_name="Подтверждение оплаты")
    registered_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")
    is_active = models.BooleanField(default=True, verbose_name="Активная регистрация")

    def __str__(self):
        return f"Регистрация {self.user} на {self.race} в мероприятии {self.event}"

    class Meta:
        verbose_name = "Регистрация на забег"
        verbose_name_plural = "Регистрации на забеги"




class EventSchedule(models.Model):
    """Model representing the schedule of a sports event."""
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="schedules", verbose_name="Мероприятие")
    start_time = models.TimeField(verbose_name="Время начала")
    description = models.CharField(max_length=255, verbose_name="Описание")

    def __str__(self):
        return f"{self.start_time.strftime('%H:%M')} - {self.description}"

    class Meta:
        verbose_name = "Программа мероприятия"
        verbose_name_plural = "Программа мероприятий"


class Organizer(models.Model):

backend/race/forms.py
from django import forms
from .models import Review, EventRegistration, Event, RaceType
from django.utils import timezone
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }


class EventRegistrationForm(forms.ModelForm):
    # Определение полей формы
    phone_number = PhoneNumberField(
        widget=forms.TextInput(),
        label='Номер телефона',
        required=True
    )

    event = forms.ModelChoiceField(
        queryset=Event.objects.filter(start_datetime__gte=timezone.now()),
        label='Мероприятие'
    )

    race = forms.ModelChoiceField(
        queryset=RaceType.objects.none(),
        label='Участвующие группы'
    )

    class Meta:
        # Конфигурация модели и определение полей, которые должны быть в форме
        model = EventRegistration
        fields = ['phone_number', 'event', 'race', 'tshirt_size', 'city', 'club', 'payment_document']

    def __init__(self, *args, **kwargs):
        # Инициализация формы
        super().__init__(*args, **kwargs)
        self.initialize_field_classes()
        self.initialize_dynamic_fields()

    def initialize_field_classes(self):
        # Установка CSS классов для каждого поля формы
        for name, field in self.fields.items():
            css_class = 'form-control' if not isinstance(field.widget, forms.widgets.Select) else 'form-select'
            field.widget.attrs.update({'class': css_class})

    def initialize_dynamic_fields(self):
        # Инициализация динамических полей, в частности, настройка queryset для поля 'race'
        event_id = self.data.get('event') if 'event' in self.data else None
        if event_id:
            self.set_race_query_set(event_id)

    def set_race_query_set(self, event_id):
        # Установка queryset для поля 'race' на основе выбранного 'event'
        try:
            event = Event.objects.get(id=event_id, start_datetime__gte=timezone.now())
            self.fields['race'].queryset = event.race_types.all()
        except (ValueError, TypeError, Event.DoesNotExist):
            self.fields['race'].queryset = RaceType.objects.none()

    def clean(self):
        # Кастомная валидация формы
        cleaned_data = super().clean()
        self.validate_event_date(cleaned_data)
        self.check_duplicate_registration(cleaned_data)
        return cleaned_data

    def validate_event_date(self, cleaned_data):
        # Проверка даты мероприятия
        event = cleaned_data.get("event")
        if event and event.start_datetime < timezone.now():
            raise forms.ValidationError("Регистрация на выбранное мероприятие уже истекла.")

    def check_duplicate_registration(self, cleaned_data):
        # Проверка на дублирование регистрации
        user = self.initial.get("user")
        event = cleaned_data.get("event")
        race = cleaned_data.get("race")
        if EventRegistration.objects.filter(user=user, event=event, race=race).exists():
            raise forms.ValidationError("Вы уже зарегистрированы на это мероприятие в данной группе.")

backend/race/templates/race/add_review.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Оставить отзыв на "{{ event.title }}"</h2>
                </div>
                <div class="card-body">
                    <form method="post" class="form">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_text" class="form-label">Текст отзыва</label>
                            {{ form.text|add_class:'form-control' }}
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить отзыв</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backend/race/templates/race/contact.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Контактная информация</h1>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Свяжитесь с нами</h5>
                    <p class="card-text"><strong>Телефон:</strong> +7 123 456 7890</p>
                    <p class="card-text"><strong>Email:</strong> <a href="mailto:info@example.com">info@example.com</a></p>
                    <p class="card-text"><strong>Адрес:</strong> г. Москва, ул. Пушкина, д. 1</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backend/race/templates/race/detailed_event.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Детали мероприятия | Организация Спортивных Мероприятий{% endblock %}

{% block content %}
    <style>
    .event-details .event-image {
    max-height: 400px; /* Максимальная высота */
    width: auto; /* Автоматическая ширина для сохранения пропорций */
    display: block; /* Устраняет проблемы с выравниванием и пространством вокруг изображения */
    margin: 0 auto; /* Центрирует изображение в контейнере */
    }
    </style>

    <!-- Заголовок мероприятия -->
    <section class="event-header py-5">
        <div class="container">
            <h1 class="display-4">{{ event.title }}</h1>
            <p class="lead">{{ event.description }}</p>
        </div>
    </section>

    <!-- Детали мероприятия -->
    <section class="event-details bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="{{ event.image.url }}" alt="{{ event.title }}" class="img-fluid event-image">
                </div>
                <div class="col-md-6">
                    <h3>Детали</h3>
                    <p><strong>Дата:</strong> {{ event.start_datetime|date:"d F Y г. (D)" }}</p>
                    <p><strong>Время:</strong> {{ event.start_datetime|time }} </p>
                    {% if event.days_left > 0 %}
                        <p class="days-left"><strong>Дней до мероприятия:</strong> {{ event.days_left }}</p>
                    {% endif %}
                    <p><strong>Свободных мест:</strong> {{ event.get_free_slots }} из {{ event.total_slots }}</p>
                    <p><strong>Местоположение:</strong> {{ event.location }}</p>
                    <p><strong>Тип мероприятия:</strong> {{ event.get_event_type_display }}</p>
                    <p><strong>Условия участия:</strong> {{ event.event_rules }}</p>
                    <!-- Кнопки -->
                    {% if user.is_authenticated %}
                        <a href="{% url 'register_for_event' %}?event_id={{ event.id }}" class="btn btn-primary">Регистрация на мероприятие</a>
                    {% else %}
                        <a href="{% url 'users:login' %}?next=/race-registration/?event_id={{ event.id }}" class="btn btn-secondary">Войти для регистрации</a>
                    {% endif %}
                    <a href="{{ event.get_registrations_url }}" class="btn btn-info">Список участников</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Интерактивная карта -->
    <section class="event-map py-5">
        <div class="container">
            <h3>Местоположение мероприятия</h3>
            <div id="map" style="height: 400px;" data-latitude="{{ latitude }}" data-longitude="{{ longitude }}"></div>
        </div>
    </section>

    <!-- Программа мероприятия -->
    <section class="event-schedule bg-light py-5">
        <div class="container">
            <h3>Программа мероприятия</h3>
            <ul>
                {% for schedule in event.schedules.all %}
                    <li>{{ schedule }}</li>
                {% endfor %}
            </ul>
        </div>
    </section>

    <!-- Участвующие группы -->
    <section class="participating-groups py-5">
        <div class="container">
            <h3>Участвующие группы</h3>
            <ul>
                {% for race_type in event.race_types.all %}
                    <li>{{ race_type }}</li>
                {% endfor %}
            </ul>
        </div>
    </section>

    <!-- ... Дальнейший контент ... -->
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'race/js/event_map.js' %}"></script>
{% endblock extra_js %}

backend/race/templates/race/event_registrations.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4 text-center">Список участников мероприятия: {{ event.title }}</h2>

    {% for race, registrations in grouped_registrations.items %}
        <div class="mb-4">
            <h5 class="mb-3">{{ race }}</h5>
            <table class="table table-bordered table-hover">
                <thead class="table-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Фамилия, имя</th>
                        <th scope="col">Город</th>
                        <th scope="col">Клуб</th>
                        <th scope="col">Год рождения</th>
                    </tr>
                </thead>
                <tbody>
                    {% for registration in registrations %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ registration.user.get_full_name }}</td>
                        <td>{{ registration.city }}</td>
                        <td>{{ registration.club }}</td>
                        <td>{{ registration.date_of_birth|date:"Y" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% empty %}
        <p class="text-center">На данный момент нет зарегистрированных участников.</p>
    {% endfor %}
</div>
{% endblock %}

backend/race/templates/race/events.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mt-4">
    <!-- Фильтры и сортировка -->
    <div class="row mb-3">
        <div class="col">
            <form method="get" class="form-inline">
                <select name="filter" class="form-select" onchange="this.form.submit()">
                    <option value="all">Все мероприятия</option>
                    <option value="upcoming" {% if filter == 'upcoming' %}selected{% endif %}>Предстоящие</option>
                    <option value="past" {% if filter == 'past' %}selected{% endif %}>Прошедшие</option>
                </select>
            </form>
        </div>
    </div>

    <!-- Список мероприятий -->
    <div class="row justify-content-center">
        {% for event in events %}
        <div class="col-md-4 d-flex align-items-stretch mb-4">
            <div class="card h-100">
                <!-- Изображение мероприятия, если оно есть -->
                {% if event.image %}
                    <img src="{{ event.image.url }}" class="card-img-top" alt="{{ event.title }}" style="height: 400px; object-fit: cover;">
                {% endif %}
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ event.title }}</h5>
                    <p class="card-text">{{ event.start_datetime|date:"d F Y г. (D)" }} {{ event.start_datetime|time }} - {{ event.location }} </p>
                    <p class="card-text">{{ event.description|truncatewords:20 }}</p>
                    <a href="{{ event.get_absolute_url }}" class="btn btn-primary mt-auto align-self-end">Подробнее</a>
                </div>
            </div>
        </div>
        {% empty %}
            <p>Мероприятия не найдены.</p>
        {% endfor %}
    </div>

    <!-- Пагинация -->
    <div class="row">
        <div class="col d-flex justify-content-center mt-4">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% for page_num in paginator.page_range %}
                        <li class="page-item {% if page == page_num %}active{% endif %}">
                            <a class="page-link" href="?page={{ page_num }}{% if filter %}&filter={{ filter }}{% endif %}">{{ page_num }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

backend/race/templates/race/pricing.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container my-4">
    <h1 class="mb-4 text-center">Информация о стоимости участия</h1>
    <div class="row justify-content-center">
        {% for event in upcoming_events %}
            <div class="col-md-6"> <!-- Здесь изменен класс -->
                <div class="card mb-3">
                    <div class="card-header text-center">
                        <h2>{{ event.title }} - {{ event.start_datetime }}</h2>
                    </div>
                    <div class="card-body">
                        <p>{{ event.description }}</p>
                        <h5 class="text-center">Типы забегов:</h5>
                        <ul class="list-group list-group-flush">
                            {% for race_type in event.race_types.all %}
                                <li class="list-group-item">
                                    {{ race_type.distance }} км {{ race_type.get_gender_display }} -
                                    {{ race_type.min_age }} лет и старше
                                    (взнос {{ race_type.registration_fee }} руб.)
                                </li>
                            {% empty %}
                                <li class="list-group-item">Информация о типах забегов для этого мероприятия отсутствует.</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="card-footer">
                        <h5 class="text-center">Организаторы:</h5>
                        <ul>
                            {% for organizer in event.organizers.all %}
                                <li>
                                    {{ organizer.user.get_full_name }} - {{ organizer.contact }}
                                    <br>Реквизиты для оплаты: {{ organizer.payment_details }}
                                </li>
                            {% empty %}
                                <li>Организаторы для этого мероприятия отсутствуют.</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% empty %}
            <p class="text-center">Предстоящие мероприятия отсутствуют.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

backend/race/templates/race/race_registration_success.html
{% extends 'layouts/base.html' %}

{% block content %}
<br>
<div class="container bg-white shadow-md p-3">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading display-4">Успешная регистрация!</h4>
        <p>
            Мы получили вашу заявку и документ об оплате. Пожалуйста, ожидайте подтверждения.<br>
            Проверить статус оплаты или отменить регистрацию на забег можно в разделе <a href="{% url 'users:registrations_list' %}">Личные регистрации</a>.<br>
            Если у вас есть какие-либо вопросы, пожалуйста, <a href="{% url 'contact' %}">Свяжитесь с нами</a>.
        </p>
    </div>
</div>
{% endblock %}